import { type Dictionary } from "intlayer";

const eventsContent = {
  key: "events",
  content: {
    en: {
      events: [
        {
          id: 1,
          title: "Being the Platinum Partner in the Egyptian Market for Honeywell Alerton BMS.",
          description: "Another Successful Milestone for Eits Automation Control Automation Contro Family in growing the business along with Honeywell in Egypt being recognized as \"New Technology Partner\" for Honeywell Alerton BMS for 2024 results & being the GOLD Parter in the Egyptian Market.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "mauritius",
          thumbnails: [
            "/platinum.jpeg",
            "/platinum-6.jpeg",
            "/platinum-1.jpeg",
            "/platinum-2.jpeg",
            "/platinum-3.jpeg",
            "/platinum-4.jpeg",
            "/platinum-5.jpeg",
            "/platinum-7.jpeg",
            "/platinum-8.jpeg",
          ],
        },
        {
          id: 2,
          title: "Being the GOLD Partner in the Egyptian Market for Honeywell Alerton BMS.",
          description: "Another Successful Milestone for Eits Automation Control Automation Contro Family in growing the business along with Honeywell in Egypt being recognized as \"New Technology Partner\" for Honeywell Alerton BMS for 2023 results & being the GOLD Parter in the Egyptian Market.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "mauritius",
          thumbnails: ["/golden.webp", "/contract.webp", "/ghazy.webp"],
        },
        {
          id: 3,
          title: "The presence of our CEO at Sontay's headquarters in the UK",
          description: "Another successful milestone for the EITS Automation Control family in expanding our presence in the Egyptian market. We are proud to be officially recognized as a 'New Technology Partner' by Sontay. This achievement was marked by the presence of our CEO at Sontay's headquarters in the UK, reflecting the strength of our partnership and our continuous commitment to bringing cutting-edge solutions to Egypt.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "UK",
          thumbnails: ["/sontay3.jpeg", "/sontay1.jpeg", "/sontay2.jpeg"],
        },
        {
          id: 7,
          title: "Our Managing Director Eng. Mohamed Ghazy with the Minister of Health and Honeywell's Executives in Egypt",
          description: "Our Managing Director, Eng. Mohamed Ghazy, met with the Minister of Health and Honeywell's senior executives in Egypt to discuss the latest achievements in advancing the healthcare sector and enhancing development efforts across the country.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egypt",
          thumbnails: ["minstry.jpeg"],
        },
        {
          id: 4,
          title: "Participation in Schneider Electric Event at Baron Hotel.",
          description: "EITS Automation Control had the honor to participate in the recent Schneider Electric event held at Baron Hotel. The event was highlighted by the attendance of a well-known TV presenter from the show 'El-Geda3an', showcasing the importance and growing recognition of our contributions in the automation and control sector.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egypt",
          thumbnails: ["/shnider1.jpeg", "/shnider2.jpeg", "/shnider3.jpeg"],
        },
        {
          id: 5,
          title: "Eits Control Annual Event 2022",
          description: "Eits family got together at \"jewel sports city hotel\" to celebrate the achievements and successes of the year and to talk about future plans. What a great opportunity to end the year on such a high note.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egypt",
          thumbnails: [
            "/team.webp",
            "/ahmed hamada.webp",
            "/engineer-Nabila.webp",
            "/hussenAbdulnasserEtis.webp",
          ],
        },
        {
          id: 6,
          title: "Eits Control Annual Event 2024",
          description: "Eits family got together at \"Ain Elhayah resort hotel\" to celebrate the achievements and successes of the year and to talk about future plans. What a great opportunity to end the year on such a high note.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egypt",
          thumbnails: [
            "/17.jpeg",
            "/2.jpeg",
            "/3.jpeg",
            "/4.jpeg",
            "/5.jpeg",
            "/6.jpeg",
            "/7.jpeg",
            "/8.jpeg",
            "/9.jpeg",
            "/10.jpeg",
            "/11.jpeg",
            "/12.jpeg",
            "/13.jpeg",
            "/14.jpeg",
            "/15.jpeg",
            "/16.jpeg",
          ],
        },
      ],
    },
    ar: {
      events: [
        {
          id: 1,
          title: "كوننا الشريك البلاتيني في السوق المصري لهونيول ألرتون BMS",
          description: "إنجاز ناجح آخر لعائلة إيتس للتحكم الآلي في تنمية الأعمال مع هونيول في مصر، حيث تم الاعتراف بنا كشريك تكنولوجي جديد لهونيول ألرتون BMS لعام 2024 وكوننا الشريك الذهبي في السوق المصري.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "موريشيوس",
          thumbnails: [
            "/platinum.jpeg",
            "/platinum-6.jpeg",
            "/platinum-1.jpeg",
            "/platinum-2.jpeg",
            "/platinum-3.jpeg",
            "/platinum-4.jpeg",
            "/platinum-5.jpeg",
            "/platinum-7.jpeg",
            "/platinum-8.jpeg",
          ],
        },
        {
          id: 2,
          title: "كوننا الشريك الذهبي في السوق المصري لهونيول ألرتون BMS",
          description: "إنجاز ناجح آخر لعائلة إيتس للتحكم الآلي في تنمية الأعمال مع هونيول في مصر، حيث تم الاعتراف بنا كشريك تكنولوجي جديد لهونيول ألرتون BMS لعام 2023 وكوننا الشريك الذهبي في السوق المصري.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "موريشيوس",
          thumbnails: ["/golden.webp", "/contract.webp", "/ghazy.webp"],
        },
        {
          id: 3,
          title: "حضور الرئيس التنفيذي في مقر سونتاي في المملكة المتحدة",
          description: "إنجاز ناجح آخر لعائلة إيتس للتحكم الآلي في توسيع وجودنا في السوق المصري. نحن فخورون بالاعتراف بنا رسمياً كشريك تكنولوجي جديد من قبل سونتاي. تميز هذا الإنجاز بحضور الرئيس التنفيذي في مقر سونتاي في المملكة المتحدة، مما يعكس قوة شراكتنا والتزامنا المستمر بتقديم حلول متطورة إلى مصر.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "المملكة المتحدة",
          thumbnails: ["/sontay3.jpeg", "/sontay1.jpeg", "/sontay2.jpeg"],
        },
        {
          id: 7,
          title: "المدير التنفيذي م. محمد غازي مع وزير الصحة وكبار مسؤولي هونيول في مصر",
          description: "التقى المدير التنفيذي م. محمد غازي مع وزير الصحة وكبار مسؤولي هونيول في مصر لمناقشة أحدث الإنجازات في تطوير قطاع الرعاية الصحية وتعزيز جهود التنمية في جميع أنحاء البلاد.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "مصر",
          thumbnails: ["minstry.jpeg"],
        },
        {
          id: 4,
          title: "المشاركة في فعالية شنايدر إلكتريك في فندق بارون",
          description: "كان لشركة إيتس للتحكم الآلي شرف المشاركة في فعالية شنايدر إلكتريك الأخيرة التي أقيمت في فندق بارون. تميز الحدث بحضور مقدم تلفزيوني معروف من برنامج 'الجدعان'، مما يبرز أهمية وتزايد الاعتراف بمساهماتنا في قطاع الأتمتة والتحكم.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "مصر",
          thumbnails: ["/shnider1.jpeg", "/shnider2.jpeg", "/shnider3.jpeg"],
        },
        {
          id: 5,
          title: "الحدث السنوي لإيتس للتحكم 2022",
          description: "اجتمعت عائلة إيتس في فندق 'جويل سبورتس سيتي' للاحتفال بإنجازات ونجاحات العام والتحدث عن الخطط المستقبلية. فرصة رائعة لإنهاء العام على هذا النحو المميز.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "مصر",
          thumbnails: [
            "/team.webp",
            "/ahmed hamada.webp",
            "/engineer-Nabila.webp",
            "/hussenAbdulnasserEtis.webp",
          ],
        },
        {
          id: 6,
          title: "الحدث السنوي لإيتس للتحكم 2024",
          description: "اجتمعت عائلة إيتس في منتجع 'عين الحياة' للاحتفال بإنجازات ونجاحات العام والتحدث عن الخطط المستقبلية. فرصة رائعة لإنهاء العام على هذا النحو المميز.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "مصر",
          thumbnails: [
            "/17.jpeg",
            "/2.jpeg",
            "/3.jpeg",
            "/4.jpeg",
            "/5.jpeg",
            "/6.jpeg",
            "/7.jpeg",
            "/8.jpeg",
            "/9.jpeg",
            "/10.jpeg",
            "/11.jpeg",
            "/12.jpeg",
            "/13.jpeg",
            "/14.jpeg",
            "/15.jpeg",
            "/16.jpeg",
          ],
        },
      ],
    },
    fr: {
      events: [
        {
          id: 1,
          title: "Devenir Partenaire Platine sur le Marché Égyptien pour Honeywell Alerton BMS",
          description: "Une autre étape réussie pour la famille Eits Automation Control dans le développement des affaires avec Honeywell en Égypte, étant reconnue comme \"Nouveau Partenaire Technologique\" pour Honeywell Alerton BMS pour les résultats 2024 et devenant Partenaire Or sur le Marché Égyptien.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Maurice",
          thumbnails: [
            "/platinum.jpeg",
            "/platinum-6.jpeg",
            "/platinum-1.jpeg",
            "/platinum-2.jpeg",
            "/platinum-3.jpeg",
            "/platinum-4.jpeg",
            "/platinum-5.jpeg",
            "/platinum-7.jpeg",
            "/platinum-8.jpeg",
          ],
        },
        {
          id: 2,
          title: "Devenir Partenaire Or sur le Marché Égyptien pour Honeywell Alerton BMS",
          description: "Une autre étape réussie pour la famille Eits Automation Control dans le développement des affaires avec Honeywell en Égypte, étant reconnue comme \"Nouveau Partenaire Technologique\" pour Honeywell Alerton BMS pour les résultats 2023 et devenant Partenaire Or sur le Marché Égyptien.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Maurice",
          thumbnails: ["/golden.webp", "/contract.webp", "/ghazy.webp"],
        },
        {
          id: 3,
          title: "La Présence de notre PDG au Siège de Sontay au Royaume-Uni",
          description: "Une autre étape réussie pour la famille EITS Automation Control dans l'expansion de notre présence sur le marché égyptien. Nous sommes fiers d'être officiellement reconnus comme 'Nouveau Partenaire Technologique' par Sontay. Cette réalisation a été marquée par la présence de notre PDG au siège de Sontay au Royaume-Uni, reflétant la force de notre partenariat et notre engagement continu à apporter des solutions de pointe en Égypte.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Royaume-Uni",
          thumbnails: ["/sontay3.jpeg", "/sontay1.jpeg", "/sontay2.jpeg"],
        },
        {
          id: 7,
          title: "Notre Directeur Général Ing. Mohamed Ghazy avec le Ministre de la Santé et les Dirigeants de Honeywell en Égypte",
          description: "Notre Directeur Général, Ing. Mohamed Ghazy, a rencontré le Ministre de la Santé et les dirigeants de Honeywell en Égypte pour discuter des dernières réalisations dans l'avancement du secteur de la santé et l'amélioration des efforts de développement à travers le pays.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Égypte",
          thumbnails: ["minstry.jpeg"],
        },
        {
          id: 4,
          title: "Participation à l'Événement Schneider Electric à l'Hôtel Baron",
          description: "EITS Automation Control a eu l'honneur de participer au récent événement Schneider Electric organisé à l'Hôtel Baron. L'événement a été marqué par la présence d'un présentateur TV bien connu de l'émission 'El-Geda3an', démontrant l'importance et la reconnaissance croissante de nos contributions dans le secteur de l'automatisation et du contrôle.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Égypte",
          thumbnails: ["/shnider1.jpeg", "/shnider2.jpeg", "/shnider3.jpeg"],
        },
        {
          id: 5,
          title: "Événement Annuel Eits Control 2022",
          description: "La famille Eits s'est réunie à l'hôtel 'jewel sports city' pour célébrer les réalisations et les succès de l'année et discuter des plans futurs. Quelle belle opportunité de terminer l'année sur une telle note positive.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Égypte",
          thumbnails: [
            "/team.webp",
            "/ahmed hamada.webp",
            "/engineer-Nabila.webp",
            "/hussenAbdulnasserEtis.webp",
          ],
        },
        {
          id: 6,
          title: "Événement Annuel Eits Control 2024",
          description: "La famille Eits s'est réunie au resort 'Ain Elhayah' pour célébrer les réalisations et les succès de l'année et discuter des plans futurs. Quelle belle opportunité de terminer l'année sur une telle note positive.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Égypte",
          thumbnails: [
            "/17.jpeg",
            "/2.jpeg",
            "/3.jpeg",
            "/4.jpeg",
            "/5.jpeg",
            "/6.jpeg",
            "/7.jpeg",
            "/8.jpeg",
            "/9.jpeg",
            "/10.jpeg",
            "/11.jpeg",
            "/12.jpeg",
            "/13.jpeg",
            "/14.jpeg",
            "/15.jpeg",
            "/16.jpeg",
          ],
        },
      ],
    },
    es: {
      events: [
        {
          id: 1,
          title: "Ser Socio Platino en el Mercado Egipcio para Honeywell Alerton BMS",
          description: "Otro hito exitoso para la familia Eits Automation Control en el crecimiento del negocio junto con Honeywell en Egipto, siendo reconocidos como \"Nuevo Socio Tecnológico\" para Honeywell Alerton BMS para los resultados de 2024 y siendo Socio Oro en el Mercado Egipcio.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Mauricio",
          thumbnails: [
            "/platinum.jpeg",
            "/platinum-6.jpeg",
            "/platinum-1.jpeg",
            "/platinum-2.jpeg",
            "/platinum-3.jpeg",
            "/platinum-4.jpeg",
            "/platinum-5.jpeg",
            "/platinum-7.jpeg",
            "/platinum-8.jpeg",
          ],
        },
        {
          id: 2,
          title: "Ser Socio Oro en el Mercado Egipcio para Honeywell Alerton BMS",
          description: "Otro hito exitoso para la familia Eits Automation Control en el crecimiento del negocio junto con Honeywell en Egipto, siendo reconocidos como \"Nuevo Socio Tecnológico\" para Honeywell Alerton BMS para los resultados de 2023 y siendo Socio Oro en el Mercado Egipcio.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Mauricio",
          thumbnails: ["/golden.webp", "/contract.webp", "/ghazy.webp"],
        },
        {
          id: 3,
          title: "La Presencia de nuestro CEO en la Sede de Sontay en el Reino Unido",
          description: "Otro hito exitoso para la familia EITS Automation Control en la expansión de nuestra presencia en el mercado egipcio. Estamos orgullosos de ser reconocidos oficialmente como 'Nuevo Socio Tecnológico' por Sontay. Este logro fue marcado por la presencia de nuestro CEO en la sede de Sontay en el Reino Unido, reflejando la fortaleza de nuestra asociación y nuestro compromiso continuo de llevar soluciones de vanguardia a Egipto.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Reino Unido",
          thumbnails: ["/sontay3.jpeg", "/sontay1.jpeg", "/sontay2.jpeg"],
        },
        {
          id: 7,
          title: "Nuestro Director General Ing. Mohamed Ghazy con el Ministro de Salud y los Ejecutivos de Honeywell en Egipto",
          description: "Nuestro Director General, Ing. Mohamed Ghazy, se reunió con el Ministro de Salud y los ejecutivos senior de Honeywell en Egipto para discutir los últimos logros en el avance del sector de la salud y la mejora de los esfuerzos de desarrollo en todo el país.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egipto",
          thumbnails: ["minstry.jpeg"],
        },
        {
          id: 4,
          title: "Participación en el Evento de Schneider Electric en el Hotel Baron",
          description: "EITS Automation Control tuvo el honor de participar en el reciente evento de Schneider Electric celebrado en el Hotel Baron. El evento fue destacado por la asistencia de un conocido presentador de TV del programa 'El-Geda3an', mostrando la importancia y el creciente reconocimiento de nuestras contribuciones en el sector de la automatización y el control.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egipto",
          thumbnails: ["/shnider1.jpeg", "/shnider2.jpeg", "/shnider3.jpeg"],
        },
        {
          id: 5,
          title: "Evento Anual de Eits Control 2022",
          description: "La familia Eits se reunió en el hotel 'jewel sports city' para celebrar los logros y éxitos del año y hablar sobre los planes futuros. Qué gran oportunidad para terminar el año con una nota tan alta.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egipto",
          thumbnails: [
            "/team.webp",
            "/ahmed hamada.webp",
            "/engineer-Nabila.webp",
            "/hussenAbdulnasserEtis.webp",
          ],
        },
        {
          id: 6,
          title: "Evento Anual de Eits Control 2024",
          description: "La familia Eits se reunió en el resort 'Ain Elhayah' para celebrar los logros y éxitos del año y hablar sobre los planes futuros. Qué gran oportunidad para terminar el año con una nota tan alta.",
          link: "https://www.linkedin.com/company/eits-automation-control/posts/?feedView=images",
          location: "Egipto",
          thumbnails: [
            "/17.jpeg",
            "/2.jpeg",
            "/3.jpeg",
            "/4.jpeg",
            "/5.jpeg",
            "/6.jpeg",
            "/7.jpeg",
            "/8.jpeg",
            "/9.jpeg",
            "/10.jpeg",
            "/11.jpeg",
            "/12.jpeg",
            "/13.jpeg",
            "/14.jpeg",
            "/15.jpeg",
            "/16.jpeg",
          ],
        },
      ],
    },
  },
} satisfies Dictionary;

export default eventsContent; 