import { type Dictionary } from "intlayer";

const projectsContent = {
  key: "projects",
  content: {
    en: {
      title: "Our Projects",
      subtitle: "Success Stories",
      description: "Explore our portfolio of successful projects across various sectors.",
      portfolio: "Portfolio",
      showing: "Showing",
      of: "of",
      projects: "projects",
      in: "in",
      matching: "matching",
      contractor: "Contractor",
      application: "Application",
      pagination: {
        previous: "Previous",
        next: "Next",
        showing: "Showing",
        of: "of",
        items: "items"
      },
      categories: {
        All: "All",
        Hospitals: "Hospitals",
        Malls: "Malls",
        Factories: "Factories",
        Hotels: "Hotels",
        Industrial: "Industrial",
        Commercial: "Commercial",
        "Data Centers": "Data Centers",
        "Data Center": "Data Center",
        Healthcare: "Healthcare",
        Government: "Government",
        Banks: "Banks",
        Airports: "Airports",
        Embassies: "Embassies",
        Pharmaceutical: "Pharmaceutical",
        Entertainment: "Entertainment",
        "Sports Facilities": "Sports Facilities"
      },
      projectNames: {
        "Esna Hospital": "Esna Hospital",
        "Port Said Hospital": "Port Said Hospital",
        "Port Foad Hospital": "Port Foad Hospital",
        "Bahr El bakr Hospital": "Bahr El bakr Hospital",
        "Hyhya Hospital": "Hyhya Hospital",
        "Assuit Hospital": "Assuit Hospital",
        "East Alex Hospital": "East Alex Hospital",
        "Concord Hospital": "Concord Hospital",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY",
        "DERMOAS HOSPITAL": "DERMOAS HOSPITAL",
        "SAMALOUT HOSPITAL": "SAMALOUT HOSPITAL",
        "SHALATIN HOSPITAL": "SHALATIN HOSPITAL",
        "EL-SALOUM HOSPITAL": "EL-SALOUM HOSPITAL",
        "ESMAILIA HOSPITAL": "ESMAILIA HOSPITAL",
        "EL-NASR PORT SAIED HOSPITAL": "EL-NASR PORT SAIED HOSPITAL",
        "BANHA HOSPITAL": "BANHA HOSPITAL",
        "AIN SHAMS HOSPITAL - BATNA 13": "AIN SHAMS HOSPITAL - BATNA 13",
        "SAMMANHOUD HOSPITAL": "SAMMANHOUD HOSPITAL",
        "NOZHA HOSPITAL": "NOZHA HOSPITAL",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED",
        "ABO EL MENAGA HOSPITAL": "ABO EL MENAGA HOSPITAL",
        "Embassy of the Netherlands": "Embassy of the Netherlands",
        "Embassy of New Zealand": "Embassy of New Zealand",
        "NILE PHARMA": "NILE PHARMA",
        "Institute Balharsia": "Institute Balharsia",
        "Aswan fever Hospital": "Aswan fever Hospital",
        "Nti National Institute for the Training of Physicians": "Nti National Institute for the Training of Physicians",
        "PEPSICO HQ Cairo Festival City": "PEPSICO HQ Cairo Festival City",
        "Authority bank - Petrojet Ras Ghareb": "Authority bank - Petrojet Ras Ghareb",
        "Authority bank - Petrojet Ras Shukair": "Authority bank - Petrojet Ras Shukair",
        "NNL Telecom Egypt data center(new capital)": "NNL Telecom Egypt data center(new capital)",
        "Port said- telecom Egypt data center": "Port said- telecom Egypt data center",
        "EL-REHAB telecom Egypt Data Center": "EL-REHAB telecom Egypt Data Center",
        "Ramad-Rod EL frag Hospital": "Ramad-Rod EL frag Hospital",
        "Wady El Nel (Admin building)": "Wady El Nel (Admin building)",
        "New Captial (Sport City)": "New Captial (Sport City)",
        "EL Robiky (Admin building)": "EL Robiky (Admin building)",
        "Blood bank (Alexandria)": "Blood bank (Alexandria)",
        "Blood bank (Tanta)": "Blood bank (Tanta)",
        "Urban Communities Authority - October": "Urban Communities Authority - October",
        "Safir Hotel (Dahab)": "Safir Hotel (Dahab)",
        "Rihanna Hotel (Marsa Alam)": "Rihanna Hotel (Marsa Alam)",
        "Nasr city (Elyoum ELwahed)": "Nasr city (Elyoum ELwahed)",
        "BETA PHARMA": "BETA PHARMA",
        "PYRAMIDS GATE": "PYRAMIDS GATE",
        "DYAR MALL": "DYAR MALL",
        "IMAGE MALL": "IMAGE MALL",
        "BADR ELDIN FOR PETROLIUM": "BADR ELDIN FOR PETROLIUM",
        "BAGHDAD AIRPORT (KARBELA HALL)": "BAGHDAD AIRPORT (KARBELA HALL)",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "PROCTER & GAMBLE - (PACKAGING EXTENTION)",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)",
        "HENKEL FACTORY - PORSAED": "HENKEL FACTORY - PORSAED",
        "HENKEL FACTORY - 6 OCTOBER": "HENKEL FACTORY - 6 OCTOBER",
        "EDITA BANI SWIF FACTORY": "EDITA BANI SWIF FACTORY",
        "FOAM FACTORY": "FOAM FACTORY",
        "BISCO MISR CAIRO FACTORY": "BISCO MISR CAIRO FACTORY",
        "Luxor International Complex": "Luxor International Complex",
        "Shobra University Hospital": "Shobra University Hospital",
        "EL Tal EL Kabir Hospital": "EL Tal EL Kabir Hospital",
        "Fayed Hospital": "Fayed Hospital",
        "Sohag children Hospital": "Sohag children Hospital",
        "Sohag university Hospital": "Sohag university Hospital",
        "Tenth of Ramadan university Hospital": "Tenth of Ramadan university Hospital",
        "30 June Hospital (kidney terminal)": "30 June Hospital (kidney terminal)",
        "EL Saff central Hospital": "EL Saff central Hospital",
        "Banha educational Hospital": "Banha educational Hospital",
        "Demerdash hospital, cosmetic department": "Demerdash hospital, cosmetic department",
        "Demerdash Hospital Combined operations": "Demerdash Hospital Combined operations",
        "EL Qanater AL khairia Hospital": "EL Qanater AL khairia Hospital",
        "EL Bagour Hospital": "EL Bagour Hospital",
        "EL Almin Hospital": "EL Almin Hospital",
        "Badr university Hospital": "Badr university Hospital",
        "EL Santa Hospital": "EL Santa Hospital",
        "Ehnasia Hospital": "Ehnasia Hospital",
        "Deshna Hospital": "Deshna Hospital",
        "Merit Hospital": "Merit Hospital",
        "Tanta General Hospital": "Tanta General Hospital",
        "Ramad EL Mataria Hospital": "Ramad EL Mataria Hospital",
        "Tanta fever Hospital": "Tanta fever Hospital",
        "Gehan Hospital": "Gehan Hospital",
        "ELDakhla Hospital": "ELDakhla Hospital",
        "Beni Ebied Hospital": "Beni Ebied Hospital",
        "Qantara East Hospital": "Qantara East Hospital",
        "Qantara West Hospital": "Qantara West Hospital",
        "Torah Hospital": "Torah Hospital",
        "Abu swer Hospital": "Abu swer Hospital",
        "grand square mall (new capital)": "grand square mall (new capital)",
        "Shanzilze mall (new capital)": "Shanzilze mall (new capital)",
        "Vois cinema(elmaza city center)": "Vois cinema(elmaza city center)",
        "pardis Hospital": "pardis Hospital",
        "B30 regenerative medicine": "B30 regenerative medicine"
      }
    },
    ar: {
      title: "معــرض",
      subtitle: "قصص النجاح",
      description: "استكشف محفظة مشاريعنا الناجحة في مختلف القطاعات.",
      portfolio: "أعمالــنا",
      showing: "عرض",
      of: "من",
      projects: "مشاريع",
      in: "في",
      matching: "مطابقة",
      contractor: "المقاول",
      application: "التطبيق",
      pagination: {
        previous: "السابق",
        next: "التالي",
        showing: "عرض",
        of: "من",
        items: "عناصر"
      },
      categories: {
        All: "الكل",
        Hospitals: "المستشفيات",
        Malls: "المولات",
        Factories: "المصانع",
        Hotels: "الفنادق",
        Industrial: "صناعي",
        Commercial: "تجاري",
        "Data Centers": "مراكز البيانات",
        "Data Center": "مركز بيانات",
        Healthcare: "الرعاية الصحية",
        Government: "حكومي",
        Banks: "البنوك",
        Airports: "المطارات",
        Embassies: "السفارات",
        Pharmaceutical: "صيدلاني",
        Entertainment: "ترفيهي",
        "Sports Facilities": "المنشآت الرياضية"
      },
      projectNames: {
        "Esna Hospital": "مستشفى إسنا",
        "Port Said Hospital": "مستشفى بورسعيد",
        "Port Foad Hospital": "مستشفى بورفؤاد",
        "Bahr El bakr Hospital": "مستشفى بحر البقر",
        "Hyhya Hospital": "مستشفى ههيا",
        "Assuit Hospital": "مستشفى أسيوط",
        "East Alex Hospital": "مستشفى شرق الإسكندرية",
        "Concord Hospital": "مستشفى كونكورد",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "جراحة الجهاز الهضمي - جامعة المنصورة",
        "DERMOAS HOSPITAL": "مستشفى درمواس",
        "SAMALOUT HOSPITAL": "مستشفى سمالوط",
        "SHALATIN HOSPITAL": "مستشفى الشلاتين",
        "EL-SALOUM HOSPITAL": "مستشفى السلوم",
        "ESMAILIA HOSPITAL": "مستشفى الإسماعيلية",
        "EL-NASR PORT SAIED HOSPITAL": "مستشفى النصر ببورسعيد",
        "BANHA HOSPITAL": "مستشفى بنها",
        "AIN SHAMS HOSPITAL - BATNA 13": "مستشفى عين شمس - بتنة 13",
        "SAMMANHOUD HOSPITAL": "مستشفى سمنود",
        "NOZHA HOSPITAL": "مستشفى النزهة",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "وحدة رعاية القلب والصدر - الشيخ زايد",
        "ABO EL MENAGA HOSPITAL": "مستشفى أبو المنجا",
        "Embassy of the Netherlands": "سفارة هولندا",
        "Embassy of New Zealand": "سفارة نيوزيلندا",
        "NILE PHARMA": "نيل فارما",
        "Institute Balharsia": "معهد البلهارسيا",
        "Aswan fever Hospital": "مستشفى حميات أسوان",
        "Nti National Institute for the Training of Physicians": "المعهد القومي لتدريب الأطباء",
        "PEPSICO HQ Cairo Festival City": "المقر الرئيسي لبيبسيكو - القاهرة فستيفال سيتي",
        "Authority bank - Petrojet Ras Ghareb": "بنك السلطة - بتروجت رأس غارب",
        "Authority bank - Petrojet Ras Shukair": "بنك السلطة - بتروجت رأس شقير",
        "NNL Telecom Egypt data center(new capital)": "مركز بيانات اتصالات مصر - العاصمة الإدارية",
        "Port said- telecom Egypt data center": "مركز بيانات اتصالات مصر - بورسعيد",
        "EL-REHAB telecom Egypt Data Center": "مركز بيانات اتصالات مصر - الرحاب",
        "Ramad-Rod EL frag Hospital": "مستشفى رمد-رود الفرج",
        "Wady El Nel (Admin building)": "وادي النيل (المبنى الإداري)",
        "New Captial (Sport City)": "العاصمة الإدارية (المدينة الرياضية)",
        "EL Robiky (Admin building)": "الروبيكي (المبنى الإداري)",
        "Blood bank (Alexandria)": "بنك الدم (الإسكندرية)",
        "Blood bank (Tanta)": "بنك الدم (طنطا)",
        "Urban Communities Authority - October": "هيئة المجتمعات العمرانية - أكتوبر",
        "Safir Hotel (Dahab)": "فندق سفير (دهب)",
        "Rihanna Hotel (Marsa Alam)": "فندق ريحانة (مرسى علم)",
        "Nasr city (Elyoum ELwahed)": "مدينة نصر (اليوم الواحد)",
        "BETA PHARMA": "بيتا فارما",
        "PYRAMIDS GATE": "بوابة الأهرامات",
        "DYAR MALL": "ديار مول",
        "IMAGE MALL": "إيماج مول",
        "BADR ELDIN FOR PETROLIUM": "بدر الدين للبترول",
        "BAGHDAD AIRPORT (KARBELA HALL)": "مطار بغداد (قاعة كربلاء)",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "بروكتر آند جامبل - (توسعة التغليف)",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "بروكتر آند جامبل - (مركز البيانات - وحدات التكييف)",
        "HENKEL FACTORY - PORSAED": "مصنع هنكل - بورسعيد",
        "HENKEL FACTORY - 6 OCTOBER": "مصنع هنكل - 6 أكتوبر",
        "EDITA BANI SWIF FACTORY": "مصنع إديتا بني سويف",
        "FOAM FACTORY": "مصنع الرغوة",
        "BISCO MISR CAIRO FACTORY": "مصنع بسكو مصر القاهرة",
        "Luxor International Complex": "المجمع الدولي للأقصر",
        "Shobra University Hospital": "مستشفى شبرا الجامعي",
        "EL Tal EL Kabir Hospital": "مستشفى التل الكبير",
        "Fayed Hospital": "مستشفى فايد",
        "Sohag children Hospital": "مستشفى سوهاج للأطفال",
        "Sohag university Hospital": "مستشفى سوهاج الجامعي",
        "Tenth of Ramadan university Hospital": "مستشفى العاشر من رمضان الجامعي",
        "30 June Hospital (kidney terminal)": "مستشفى 30 يونيو (قسم الكلى)",
        "EL Saff central Hospital": "مستشفى الصف المركزي",
        "Banha educational Hospital": "مستشفى بنها التعليمي",
        "Demerdash hospital, cosmetic department": "مستشفى الدمرداش، قسم التجميل",
        "Demerdash Hospital Combined operations": "مستشفى الدمرداش العمليات المشتركة",
        "EL Qanater AL khairia Hospital": "مستشفى القناطر الخيرية",
        "EL Bagour Hospital": "مستشفى الباجور",
        "EL Almin Hospital": "مستشفى العليمين",
        "Badr university Hospital": "مستشفى بدر الجامعي",
        "EL Santa Hospital": "مستشفى السنتا",
        "Ehnasia Hospital": "مستشفى إهناسيا",
        "Deshna Hospital": "مستشفى دشنا",
        "Merit Hospital": "مستشفى ميريت",
        "Tanta General Hospital": "مستشفى طنطا العام",
        "Ramad EL Mataria Hospital": "مستشفى رمد المطرية",
        "Tanta fever Hospital": "مستشفى حميات طنطا",
        "Gehan Hospital": "مستشفى جيهان",
        "ELDakhla Hospital": "مستشفى الداخلة",
        "Beni Ebied Hospital": "مستشفى بني عبيد",
        "Qantara East Hospital": "مستشفى القنطرة شرق",
        "Qantara West Hospital": "مستشفى القنطرة غرب",
        "Torah Hospital": "مستشفى طرة",
        "Abu swer Hospital": "مستشفى أبو صوير",
        "grand square mall (new capital)": "جراند سكوير مول (العاصمة الإدارية)",
        "Shanzilze mall (new capital)": "شانزليز مول (العاصمة الإدارية)",
        "Vois cinema(elmaza city center)": "سينما فويس (مركز مدينة الماظة)",
        "pardis Hospital": "مستشفى باراديس",
        "B30 regenerative medicine": "B30 الطب التجديدي"
      }
    },
    fr: {
      title: "Nos Projets",
      subtitle: "Histoires de Réussite",
      description: "Explorez notre portefeuille de projets réussis dans divers secteurs.",
      portfolio: "Portefeuille",
      showing: "Affichage",
      of: "sur",
      projects: "projets",
      in: "dans",
      matching: "correspondant à",
      contractor: "Entrepreneur",
      application: "Application",
      pagination: {
        previous: "Précédent",
        next: "Suivant",
        showing: "Affichage",
        of: "sur",
        items: "éléments"
      },
      categories: {
        All: "Tous",
        Hospitals: "Hôpitaux",
        Malls: "Centres commerciaux",
        Factories: "Usines",
        Hotels: "Hôtels",
        Industrial: "Industriel",
        Commercial: "Commercial",
        "Data Centers": "Centres de données",
        "Data Center": "Centre de données",
        Healthcare: "Santé",
        Government: "Gouvernement",
        Banks: "Banques",
        Airports: "Aéroports",
        Embassies: "Ambassades",
        Pharmaceutical: "Pharmaceutique",
        Entertainment: "Divertissement",
        "Sports Facilities": "Installations sportives"
      },
      projectNames: {
        "Esna Hospital": "Hôpital d'Esna",
        "Port Said Hospital": "Hôpital de Port-Saïd",
        "Port Foad Hospital": "Hôpital de Port-Fouad",
        "Bahr El bakr Hospital": "Hôpital Bahr El Bakr",
        "Hyhya Hospital": "Hôpital Hyhya",
        "Assuit Hospital": "Hôpital d'Assiout",
        "East Alex Hospital": "Hôpital d'Alexandrie Est",
        "Concord Hospital": "Hôpital Concord",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "Chirurgie Gastro-intestinale - Université de Mansoura",
        "DERMOAS HOSPITAL": "Hôpital Dermoas",
        "SAMALOUT HOSPITAL": "Hôpital Samalout",
        "SHALATIN HOSPITAL": "Hôpital Shalatin",
        "EL-SALOUM HOSPITAL": "Hôpital El-Saloum",
        "ESMAILIA HOSPITAL": "Hôpital d'Ismaïlia",
        "EL-NASR PORT SAIED HOSPITAL": "Hôpital El-Nasr de Port-Saïd",
        "BANHA HOSPITAL": "Hôpital de Banha",
        "AIN SHAMS HOSPITAL - BATNA 13": "Hôpital Ain Shams - Batna 13",
        "SAMMANHOUD HOSPITAL": "Hôpital Sammanhoud",
        "NOZHA HOSPITAL": "Hôpital Nozha",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "Unité de Soins Cardiaques et Thoraciques - Cheikh Zayed",
        "ABO EL MENAGA HOSPITAL": "Hôpital Abo El Menaga",
        "Embassy of the Netherlands": "Ambassade des Pays-Bas",
        "Embassy of New Zealand": "Ambassade de Nouvelle-Zélande",
        "NILE PHARMA": "Nile Pharma",
        "Institute Balharsia": "Institut Balharsia",
        "Aswan fever Hospital": "Hôpital de Fièvre d'Assouan",
        "Nti National Institute for the Training of Physicians": "Institut National de Formation des Médecins",
        "PEPSICO HQ Cairo Festival City": "Siège de PEPSICO - Cairo Festival City",
        "Authority bank - Petrojet Ras Ghareb": "Banque d'Autorité - Petrojet Ras Ghareb",
        "Authority bank - Petrojet Ras Shukair": "Banque d'Autorité - Petrojet Ras Shukair",
        "NNL Telecom Egypt data center(new capital)": "Centre de données Telecom Egypt - Nouvelle Capitale",
        "Port said- telecom Egypt data center": "Centre de données Telecom Egypt - Port-Saïd",
        "EL-REHAB telecom Egypt Data Center": "Centre de données Telecom Egypt - El-Rehab",
        "Ramad-Rod EL frag Hospital": "Hôpital Ramad-Rod El Frag",
        "Wady El Nel (Admin building)": "Wady El Nel (Bâtiment administratif)",
        "New Captial (Sport City)": "Nouvelle Capitale (Cité Sportive)",
        "EL Robiky (Admin building)": "El Robiky (Bâtiment administratif)",
        "Blood bank (Alexandria)": "Banque de sang (Alexandrie)",
        "Blood bank (Tanta)": "Banque de sang (Tanta)",
        "Urban Communities Authority - October": "Autorité des Communautés Urbaines - Octobre",
        "Safir Hotel (Dahab)": "Hôtel Safir (Dahab)",
        "Rihanna Hotel (Marsa Alam)": "Hôtel Rihanna (Marsa Alam)",
        "Nasr city (Elyoum ELwahed)": "Ville de Nasr (Elyoum Elwahed)",
        "BETA PHARMA": "BETA PHARMA",
        "PYRAMIDS GATE": "PYRAMIDS GATE",
        "DYAR MALL": "DYAR MALL",
        "IMAGE MALL": "IMAGE MALL",
        "BADR ELDIN FOR PETROLIUM": "BADR ELDIN FOR PETROLIUM",
        "BAGHDAD AIRPORT (KARBELA HALL)": "Aéroport de Bagdad (Hall Karbela)",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "Procter & Gamble - (Extension d'emballage)",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "Procter & Gamble - (Centre de données - Unités AC)",
        "HENKEL FACTORY - PORSAED": "Usine Henkel - Port-Saïd",
        "HENKEL FACTORY - 6 OCTOBER": "Usine Henkel - 6 Octobre",
        "EDITA BANI SWIF FACTORY": "Usine Edita Bani Swif",
        "FOAM FACTORY": "Usine de Mousse",
        "BISCO MISR CAIRO FACTORY": "Usine Bisco Misr Le Caire",
        "Luxor International Complex": "Complexe International de Louxor",
        "Shobra University Hospital": "Hôpital Universitaire de Shobra",
        "EL Tal EL Kabir Hospital": "Hôpital El Tal El Kabir",
        "Fayed Hospital": "Hôpital Fayed",
        "Sohag children Hospital": "Hôpital pour Enfants de Sohag",
        "Sohag university Hospital": "Hôpital Universitaire de Sohag",
        "Tenth of Ramadan university Hospital": "Hôpital Universitaire du 10 Ramadan",
        "30 June Hospital (kidney terminal)": "Hôpital du 30 Juin (Terminal rénal)",
        "EL Saff central Hospital": "Hôpital Central d'El Saff",
        "Banha educational Hospital": "Hôpital Éducatif de Banha",
        "Demerdash hospital, cosmetic department": "Hôpital Demerdash, Département de Cosmétique",
        "Demerdash Hospital Combined operations": "Hôpital Demerdash Opérations Combinées",
        "EL Qanater AL khairia Hospital": "Hôpital El Qanater Al Khairia",
        "EL Bagour Hospital": "Hôpital El Bagour",
        "EL Almin Hospital": "Hôpital El Almin",
        "Badr university Hospital": "Hôpital Universitaire de Badr",
        "EL Santa Hospital": "Hôpital El Santa",
        "Ehnasia Hospital": "Hôpital Ehnasia",
        "Deshna Hospital": "Hôpital Deshna",
        "Merit Hospital": "Hôpital Merit",
        "Tanta General Hospital": "Hôpital Général de Tanta",
        "Ramad EL Mataria Hospital": "Hôpital Ramad El Mataria",
        "Tanta fever Hospital": "Hôpital de Fièvre de Tanta",
        "Gehan Hospital": "Hôpital Gehan",
        "ELDakhla Hospital": "Hôpital El Dakhla",
        "Beni Ebied Hospital": "Hôpital Beni Ebied",
        "Qantara East Hospital": "Hôpital Qantara Est",
        "Qantara West Hospital": "Hôpital Qantara Ouest",
        "Torah Hospital": "Hôpital Torah",
        "Abu swer Hospital": "Hôpital Abu Swer",
        "grand square mall (new capital)": "Centre Commercial Grand Square (Nouvelle Capitale)",
        "Shanzilze mall (new capital)": "Centre Commercial Shanzilze (Nouvelle Capitale)",
        "Vois cinema(elmaza city center)": "Cinéma Vois (Centre-ville d'Elmaza)",
        "pardis Hospital": "Hôpital Pardis",
        "B30 regenerative medicine": "B30 Médecine Régénérative"
      }
    },
    es: {
      title: "Nuestros Proyectos",
      subtitle: "Historias de Éxito",
      description: "Explore nuestro portafolio de proyectos exitosos en varios sectores.",
      portfolio: "Portafolio",
      showing: "Mostrando",
      of: "de",
      projects: "proyectos",
      in: "en",
      matching: "coincidiendo con",
      contractor: "Contratista",
      application: "Aplicación",
      pagination: {
        previous: "Anterior",
        next: "Siguiente",
        showing: "Mostrando",
        of: "de",
        items: "elementos"
      },
      categories: {
        All: "Todos",
        Hospitals: "Hospitales",
        Malls: "Centros comerciales",
        Factories: "Fábricas",
        Hotels: "Hoteles",
        Industrial: "Industrial",
        Commercial: "Comercial",
        "Data Centers": "Centros de datos",
        "Data Center": "Centro de datos",
        Healthcare: "Salud",
        Government: "Gobierno",
        Banks: "Bancos",
        Airports: "Aeropuertos",
        Embassies: "Embajadas",
        Pharmaceutical: "Farmacéutico",
        Entertainment: "Entretenimiento",
        "Sports Facilities": "Instalaciones deportivas"
      },
      projectNames: {
        "Esna Hospital": "Hospital de Esna",
        "Port Said Hospital": "Hospital de Port Said",
        "Port Foad Hospital": "Hospital de Port Foad",
        "Bahr El bakr Hospital": "Hospital Bahr El Bakr",
        "Hyhya Hospital": "Hospital Hyhya",
        "Assuit Hospital": "Hospital de Assuit",
        "East Alex Hospital": "Hospital Este de Alejandría",
        "Concord Hospital": "Hospital Concord",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "Cirugía Gastrointestinal - Universidad de Mansoura",
        "DERMOAS HOSPITAL": "Hospital Dermoas",
        "SAMALOUT HOSPITAL": "Hospital Samalout",
        "SHALATIN HOSPITAL": "Hospital Shalatin",
        "EL-SALOUM HOSPITAL": "Hospital El-Saloum",
        "ESMAILIA HOSPITAL": "Hospital de Ismailia",
        "EL-NASR PORT SAIED HOSPITAL": "Hospital El-Nasr de Port Said",
        "BANHA HOSPITAL": "Hospital de Banha",
        "AIN SHAMS HOSPITAL - BATNA 13": "Hospital Ain Shams - Batna 13",
        "SAMMANHOUD HOSPITAL": "Hospital Sammanhoud",
        "NOZHA HOSPITAL": "Hospital Nozha",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "Unidad de Cuidados Cardíacos y Torácicos - Sheikh Zayed",
        "ABO EL MENAGA HOSPITAL": "Hospital Abo El Menaga",
        "Embassy of the Netherlands": "Embajada de los Países Bajos",
        "Embassy of New Zealand": "Embajada de Nueva Zelanda",
        "NILE PHARMA": "Nile Pharma",
        "Institute Balharsia": "Instituto Balharsia",
        "Aswan fever Hospital": "Hospital de Fiebre de Asuán",
        "Nti National Institute for the Training of Physicians": "Instituto Nacional de Formación de Médicos",
        "PEPSICO HQ Cairo Festival City": "Sede de PEPSICO - Cairo Festival City",
        "Authority bank - Petrojet Ras Ghareb": "Banco de Autoridad - Petrojet Ras Ghareb",
        "Authority bank - Petrojet Ras Shukair": "Banco de Autoridad - Petrojet Ras Shukair",
        "NNL Telecom Egypt data center(new capital)": "Centro de datos de Telecom Egypt - Nueva Capital",
        "Port said- telecom Egypt data center": "Centro de datos de Telecom Egypt - Port Said",
        "EL-REHAB telecom Egypt Data Center": "Centro de datos de Telecom Egypt - El-Rehab",
        "Ramad-Rod EL frag Hospital": "Hospital Ramad-Rod El Frag",
        "Wady El Nel (Admin building)": "Wady El Nel (Edificio administrativo)",
        "New Captial (Sport City)": "Nueva Capital (Ciudad Deportiva)",
        "EL Robiky (Admin building)": "El Robiky (Edificio administrativo)",
        "Blood bank (Alexandria)": "Banco de sangre (Alejandría)",
        "Blood bank (Tanta)": "Banco de sangre (Tanta)",
        "Urban Communities Authority - October": "Autoridad de Comunidades Urbanas - Octubre",
        "Safir Hotel (Dahab)": "Hotel Safir (Dahab)",
        "Rihanna Hotel (Marsa Alam)": "Hotel Rihanna (Marsa Alam)",
        "Nasr city (Elyoum ELwahed)": "Ciudad Nasr (Elyoum Elwahed)",
        "BETA PHARMA": "BETA PHARMA",
        "PYRAMIDS GATE": "PYRAMIDS GATE",
        "DYAR MALL": "DYAR MALL",
        "IMAGE MALL": "IMAGE MALL",
        "BADR ELDIN FOR PETROLIUM": "BADR ELDIN FOR PETROLIUM",
        "BAGHDAD AIRPORT (KARBELA HALL)": "Aeropuerto de Bagdad (Sala Karbela)",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "Procter & Gamble - (Extensión de Embalaje)",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "Procter & Gamble - (Centro de Datos - Unidades AC)",
        "HENKEL FACTORY - PORSAED": "Fábrica Henkel - Port Said",
        "HENKEL FACTORY - 6 OCTOBER": "Fábrica Henkel - 6 de Octubre",
        "EDITA BANI SWIF FACTORY": "Fábrica Edita Bani Swif",
        "FOAM FACTORY": "Fábrica de Espuma",
        "BISCO MISR CAIRO FACTORY": "Fábrica Bisco Misr El Cairo",
        "Luxor International Complex": "Complejo Internacional de Luxor",
        "Shobra University Hospital": "Hospital Universitario de Shobra",
        "EL Tal EL Kabir Hospital": "Hospital El Tal El Kabir",
        "Fayed Hospital": "Hospital Fayed",
        "Sohag children Hospital": "Hospital Infantil de Sohag",
        "Sohag university Hospital": "Hospital Universitario de Sohag",
        "Tenth of Ramadan university Hospital": "Hospital Universitario del 10 de Ramadán",
        "30 June Hospital (kidney terminal)": "Hospital 30 de Junio (Terminal Renal)",
        "EL Saff central Hospital": "Hospital Central de El Saff",
        "Banha educational Hospital": "Hospital Educativo de Banha",
        "Demerdash hospital, cosmetic department": "Hospital Demerdash, Departamento de Cosmética",
        "Demerdash Hospital Combined operations": "Hospital Demerdash Operaciones Combinadas",
        "EL Qanater AL khairia Hospital": "Hospital El Qanater Al Khairia",
        "EL Bagour Hospital": "Hospital El Bagour",
        "EL Almin Hospital": "Hospital El Almin",
        "Badr university Hospital": "Hospital Universitario de Badr",
        "EL Santa Hospital": "Hospital El Santa",
        "Ehnasia Hospital": "Hospital Ehnasia",
        "Deshna Hospital": "Hospital Deshna",
        "Merit Hospital": "Hospital Merit",
        "Tanta General Hospital": "Hospital General de Tanta",
        "Ramad EL Mataria Hospital": "Hospital Ramad El Mataria",
        "Tanta fever Hospital": "Hospital de Fiebre de Tanta",
        "Gehan Hospital": "Hospital Gehan",
        "ELDakhla Hospital": "Hospital El Dakhla",
        "Beni Ebied Hospital": "Hospital Beni Ebied",
        "Qantara East Hospital": "Hospital Qantara Este",
        "Qantara West Hospital": "Hospital Qantara Oeste",
        "Torah Hospital": "Hospital Torah",
        "Abu swer Hospital": "Hospital Abu Swer",
        "grand square mall (new capital)": "Centro Comercial Grand Square (Nueva Capital)",
        "Shanzilze mall (new capital)": "Centro Comercial Shanzilze (Nueva Capital)",
        "Vois cinema(elmaza city center)": "Cine Vois (Centro de la Ciudad de Elmaza)",
        "pardis Hospital": "Hospital Pardis",
        "B30 regenerative medicine": "B30 Medicina Regenerativa"
      }
    },
    de: {
      title: "Unsere Projekte",
      subtitle: "Erfolgsgeschichten",
      description: "Entdecken Sie unser Portfolio erfolgreicher Projekte in verschiedenen Sektoren.",
      portfolio: "Portfolio",
      showing: "Anzeige",
      of: "von",
      projects: "Projekte",
      in: "in",
      matching: "passend zu",
      contractor: "Auftragnehmer",
      application: "Anwendung",
      pagination: {
        previous: "Zurück",
        next: "Weiter",
        showing: "Anzeige",
        of: "von",
        items: "Elemente"
      },
      categories: {
        All: "Alle",
        Hospitals: "Krankenhäuser",
        Malls: "Einkaufszentren",
        Factories: "Fabriken",
        Hotels: "Hotels",
        Industrial: "Industriell",
        Commercial: "Kommerziell",
        "Data Centers": "Rechenzentren",
        "Data Center": "Rechenzentrum",
        Healthcare: "Gesundheitswesen",
        Government: "Regierung",
        Banks: "Banken",
        Airports: "Flughäfen",
        Embassies: "Botschaften",
        Pharmaceutical: "Pharmazeutisch",
        Entertainment: "Unterhaltung",
        "Sports Facilities": "Sportanlagen"
      },
      projectNames: {
        "Esna Hospital": "Krankenhaus Esna",
        "Port Said Hospital": "Krankenhaus Port Said",
        "Port Foad Hospital": "Krankenhaus Port Foad",
        "Bahr El bakr Hospital": "Krankenhaus Bahr El Bakr",
        "Hyhya Hospital": "Krankenhaus Hyhya",
        "Assuit Hospital": "Krankenhaus Assiut",
        "East Alex Hospital": "Ost-Alexandria Krankenhaus",
        "Concord Hospital": "Krankenhaus Concord",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "Gastrointestinale Chirurgie - Universität Mansoura",
        "DERMOAS HOSPITAL": "Krankenhaus Dermoas",
        "SAMALOUT HOSPITAL": "Krankenhaus Samalout",
        "SHALATIN HOSPITAL": "Krankenhaus Shalatin",
        "EL-SALOUM HOSPITAL": "Krankenhaus El-Saloum",
        "ESMAILIA HOSPITAL": "Krankenhaus Ismailia",
        "EL-NASR PORT SAIED HOSPITAL": "Krankenhaus El-Nasr Port Said",
        "BANHA HOSPITAL": "Krankenhaus Banha",
        "AIN SHAMS HOSPITAL - BATNA 13": "Krankenhaus Ain Shams - Batna 13",
        "SAMMANHOUD HOSPITAL": "Krankenhaus Sammanhoud",
        "NOZHA HOSPITAL": "Krankenhaus Nozha",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "Herz- und Thoraxpflegeeinheit - Sheikh Zayed",
        "ABO EL MENAGA HOSPITAL": "Krankenhaus Abo El Menaga",
        "Embassy of the Netherlands": "Botschaft der Niederlande",
        "Embassy of New Zealand": "Botschaft von Neuseeland",
        "NILE PHARMA": "Nile Pharma",
        "Institute Balharsia": "Institut Balharsia",
        "Aswan fever Hospital": "Fieberkrankenhaus Assuan",
        "Nti National Institute for the Training of Physicians": "Nationales Institut für Ärzteausbildung",
        "PEPSICO HQ Cairo Festival City": "PEPSICO Hauptsitz - Cairo Festival City",
        "Authority bank - Petrojet Ras Ghareb": "Behördenbank - Petrojet Ras Ghareb",
        "Authority bank - Petrojet Ras Shukair": "Behördenbank - Petrojet Ras Shukair",
        "NNL Telecom Egypt data center(new capital)": "Telecom Ägypten Rechenzentrum - Nouvelle Capitale",
        "Port said- telecom Egypt data center": "Telecom Ägypten Rechenzentrum - Port Said",
        "EL-REHAB telecom Egypt Data Center": "Telecom Ägypten Rechenzentrum - El-Rehab",
        "Ramad-Rod EL frag Hospital": "Krankenhaus Ramad-Rod El Frag",
        "Wady El Nel (Admin building)": "Wady El Nel (Verwaltungsgebäude)",
        "New Captial (Sport City)": "Neue Hauptstadt (Sportstadt)",
        "EL Robiky (Admin building)": "El Robiky (Verwaltungsgebäude)",
        "Blood bank (Alexandria)": "Blutbank (Alexandria)",
        "Blood bank (Tanta)": "Blutbank (Tanta)",
        "Urban Communities Authority - October": "Behörde für städtische Gemeinschaften - Oktober",
        "Safir Hotel (Dahab)": "Safir Hotel (Dahab)",
        "Rihanna Hotel (Marsa Alam)": "Rihanna Hotel (Marsa Alam)",
        "Nasr city (Elyoum ELwahed)": "Nasr Stadt (Elyoum Elwahed)",
        "BETA PHARMA": "BETA PHARMA",
        "PYRAMIDS GATE": "PYRAMIDS GATE",
        "DYAR MALL": "DYAR MALL",
        "IMAGE MALL": "IMAGE MALL",
        "BADR ELDIN FOR PETROLIUM": "BADR ELDIN FOR PETROLIUM",
        "BAGHDAD AIRPORT (KARBELA HALL)": "Flughafen Bagdad (Karbela-Halle)",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "Procter & Gamble - (Verpackungserweiterung)",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "Procter & Gamble - (Rechenzentrum - AC-Einheiten)",
        "HENKEL FACTORY - PORSAED": "Henkel-Fabrik - Port Said",
        "HENKEL FACTORY - 6 OCTOBER": "Henkel-Fabrik - 6. Oktober",
        "EDITA BANI SWIF FACTORY": "Edita Bani Swif Fabrik",
        "FOAM FACTORY": "Schaumfabrik",
        "BISCO MISR CAIRO FACTORY": "Bisco Misr Kairo Fabrik",
        "Luxor International Complex": "Luxor Internationaler Komplex",
        "Shobra University Hospital": "Shobra Universitätskrankenhaus",
        "EL Tal EL Kabir Hospital": "EL Tal EL Kabir Krankenhaus",
        "Fayed Hospital": "Fayed Krankenhaus",
        "Sohag children Hospital": "Sohag Kinderkrankenhaus",
        "Sohag university Hospital": "Sohag Universitätskrankenhaus",
        "Tenth of Ramadan university Hospital": "10. Ramadan Universitätskrankenhaus",
        "30 June Hospital (kidney terminal)": "30. Juni Krankenhaus (Nierenstation)",
        "EL Saff central Hospital": "EL Saff Zentralkrankenhaus",
        "Banha educational Hospital": "Banha Bildungskrankenhaus",
        "Demerdash hospital, cosmetic department": "Demerdash Krankenhaus, Kosmetikabteilung",
        "Demerdash Hospital Combined operations": "Demerdash Krankenhaus Kombinierte Operationen",
        "EL Qanater AL khairia Hospital": "EL Qanater AL khairia Krankenhaus",
        "EL Bagour Hospital": "EL Bagour Krankenhaus",
        "EL Almin Hospital": "EL Almin Krankenhaus",
        "Badr university Hospital": "Badr Universitätskrankenhaus",
        "EL Santa Hospital": "EL Santa Krankenhaus",
        "Ehnasia Hospital": "Ehnasia Krankenhaus",
        "Deshna Hospital": "Deshna Krankenhaus",
        "Merit Hospital": "Merit Krankenhaus",
        "Tanta General Hospital": "Tanta Allgemeinkrankenhaus",
        "Ramad EL Mataria Hospital": "Ramad EL Mataria Krankenhaus",
        "Tanta fever Hospital": "Tanta Fieberkrankenhaus",
        "Gehan Hospital": "Gehan Krankenhaus",
        "ELDakhla Hospital": "ELDakhla Krankenhaus",
        "Beni Ebied Hospital": "Beni Ebied Krankenhaus",
        "Qantara East Hospital": "Qantara Ost Krankenhaus",
        "Qantara West Hospital": "Qantara West Krankenhaus",
        "Torah Hospital": "Torah Krankenhaus",
        "Abu swer Hospital": "Abu swer Krankenhaus",
        "grand square mall (new capital)": "Grand Square Einkaufszentrum (Neue Hauptstadt)",
        "Shanzilze mall (new capital)": "Shanzilze Einkaufszentrum (Neue Hauptstadt)",
        "Vois cinema(elmaza city center)": "Vois Kino (Elmaza Stadtzentrum)",
        "pardis Hospital": "Pardis Krankenhaus",
        "B30 regenerative medicine": "B30 Regenerative Medizin"
      }
    },
    zh: {
      title: "我们的项目",
      subtitle: "成功案例",
      description: "探索我们在各个领域的成功项目组合。",
      portfolio: "项目组合",
      showing: "显示",
      of: "共",
      projects: "个项目",
      in: "在",
      matching: "匹配",
      contractor: "承包商",
      application: "应用",
      pagination: {
        previous: "上一页",
        next: "下一页",
        showing: "显示",
        of: "共",
        items: "个项目"
      },
      categories: {
        All: "全部",
        Hospitals: "医院",
        Malls: "购物中心",
        Factories: "工厂",
        Hotels: "酒店",
        Industrial: "工业",
        Commercial: "商业",
        "Data Centers": "数据中心",
        "Data Center": "数据中心",
        Healthcare: "医疗保健",
        Government: "政府",
        Banks: "银行",
        Airports: "机场",
        Embassies: "大使馆",
        Pharmaceutical: "制药",
        Entertainment: "娱乐",
        "Sports Facilities": "体育设施"
      },
      projectNames: {
        "Esna Hospital": "伊斯纳医院",
        "Port Said Hospital": "塞得港医院",
        "Port Foad Hospital": "福阿德港医院",
        "Bahr El bakr Hospital": "巴赫埃尔巴克尔医院",
        "Hyhya Hospital": "海亚医院",
        "Assuit Hospital": "艾斯尤特医院",
        "East Alex Hospital": "东亚历山大医院",
        "Concord Hospital": "协和医院",
        "GASTROINTESTINAL SURGERY - MASOURA UNIVERSITY": "胃肠外科 - 曼苏拉大学",
        "DERMOAS HOSPITAL": "德尔莫阿斯医院",
        "SAMALOUT HOSPITAL": "萨马卢特医院",
        "SHALATIN HOSPITAL": "沙拉廷医院",
        "EL-SALOUM HOSPITAL": "埃尔萨卢姆医院",
        "ESMAILIA HOSPITAL": "伊斯梅利亚医院",
        "EL-NASR PORT SAIED HOSPITAL": "埃尔纳斯尔塞得港医院",
        "BANHA HOSPITAL": "本哈医院",
        "AIN SHAMS HOSPITAL - BATNA 13": "艾因沙姆斯医院 - 巴特纳13",
        "SAMMANHOUD HOSPITAL": "萨曼胡德医院",
        "NOZHA HOSPITAL": "努兹哈医院",
        "CARDIAC AND CHEST CARE UNIT- ELSHIKH ZAYED": "心脏和胸部护理单元 - 谢赫扎耶德",
        "ABO EL MENAGA HOSPITAL": "阿布埃尔梅纳加医院",
        "Embassy of the Netherlands": "荷兰大使馆",
        "Embassy of New Zealand": "新西兰大使馆",
        "NILE PHARMA": "尼罗制药",
        "Institute Balharsia": "巴尔哈西亚研究所",
        "Aswan fever Hospital": "阿斯旺发热医院",
        "Nti National Institute for the Training of Physicians": "国家医师培训研究所",
        "PEPSICO HQ Cairo Festival City": "百事可乐总部 - 开罗节日城",
        "Authority bank - Petrojet Ras Ghareb": "权威银行 - 石油公司拉斯加里布",
        "Authority bank - Petrojet Ras Shukair": "权威银行 - 石油公司拉斯舒凯尔",
        "NNL Telecom Egypt data center(new capital)": "埃及电信数据中心 - 新首都",
        "Port said- telecom Egypt data center": "埃及电信数据中心 - 塞得港",
        "EL-REHAB telecom Egypt Data Center": "埃及电信数据中心 - 埃尔雷哈布",
        "Ramad-Rod EL frag Hospital": "拉马德-罗德埃尔弗拉格医院",
        "Wady El Nel (Admin building)": "瓦迪埃尔内尔（行政大楼）",
        "New Captial (Sport City)": "新首都（体育城）",
        "EL Robiky (Admin building)": "埃尔罗比基（行政大楼）",
        "Blood bank (Alexandria)": "血库（亚历山大）",
        "Blood bank (Tanta)": "血库（坦塔）",
        "Urban Communities Authority - October": "城市社区管理局 - 十月",
        "Safir Hotel (Dahab)": "萨菲尔酒店（达哈布）",
        "Rihanna Hotel (Marsa Alam)": "蕾哈娜酒店（马萨阿拉姆）",
        "Nasr city (Elyoum ELwahed)": "纳斯尔城（埃利乌姆埃尔瓦希德）",
        "BETA PHARMA": "BETA PHARMA",
        "PYRAMIDS GATE": "PYRAMIDS GATE",
        "DYAR MALL": "DYAR MALL",
        "IMAGE MALL": "IMAGE MALL",
        "BADR ELDIN FOR PETROLIUM": "BADR ELDIN FOR PETROLIUM",
        "BAGHDAD AIRPORT (KARBELA HALL)": "巴格达机场（卡尔巴拉大厅）",
        "PROCTER & GAMBLE - (PACKAGING EXTENTION)": "宝洁公司 - （包装扩展）",
        "PROCTER & GAMBLE - (DATA CENTER - AC UNITS)": "宝洁公司 - （数据中心 - 空调机组）",
        "HENKEL FACTORY - PORSAED": "汉高工厂 - 塞得港",
        "HENKEL FACTORY - 6 OCTOBER": "汉高工厂 - 十月六日城",
        "EDITA BANI SWIF FACTORY": "艾迪塔巴尼苏维夫工厂",
        "FOAM FACTORY": "泡沫工厂",
        "BISCO MISR CAIRO FACTORY": "比斯科埃及开罗工厂",
        "Luxor International Complex": "卢克索国际综合体",
        "Shobra University Hospital": "舒布拉大学医院",
        "EL Tal EL Kabir Hospital": "塔尔卡比尔医院",
        "Fayed Hospital": "法耶德医院",
        "Sohag children Hospital": "索哈杰儿童医院",
        "Sohag university Hospital": "索哈杰大学医院",
        "Tenth of Ramadan university Hospital": "斋月十日大学医院",
        "30 June Hospital (kidney terminal)": "六月三十日医院（肾脏科）",
        "EL Saff central Hospital": "萨夫中心医院",
        "Banha educational Hospital": "本哈教育医院",
        "Demerdash hospital, cosmetic department": "德默达什医院，美容科",
        "Demerdash Hospital Combined operations": "德默达什医院综合手术部",
        "EL Qanater AL khairia Hospital": "坎塔拉慈善医院",
        "EL Bagour Hospital": "巴古尔医院",
        "EL Almin Hospital": "阿明医院",
        "Badr university Hospital": "巴德尔大学医院",
        "EL Santa Hospital": "圣塔医院",
        "Ehnasia Hospital": "埃纳西亚医院",
        "Deshna Hospital": "德什纳医院",
        "Merit Hospital": "梅里特医院",
        "Tanta General Hospital": "坦塔综合医院",
        "Ramad EL Mataria Hospital": "拉马德马塔里亚医院",
        "Tanta fever Hospital": "坦塔发热医院",
        "Gehan Hospital": "吉汉医院",
        "ELDakhla Hospital": "达赫拉医院",
        "Beni Ebied Hospital": "贝尼埃比德医院",
        "Qantara East Hospital": "坎塔拉东医院",
        "Qantara West Hospital": "坎塔拉西医院",
        "Torah Hospital": "托拉医院",
        "Abu swer Hospital": "阿布苏维尔医院",
        "grand square mall (new capital)": "大广场购物中心（新首都）",
        "Shanzilze mall (new capital)": "香榭丽舍购物中心（新首都）",
        "Vois cinema(elmaza city center)": "沃伊斯电影院（马扎市中心）",
        "pardis Hospital": "帕尔迪斯医院",
        "B30 regenerative medicine": "B30再生医学"
      }
    }
  }
} satisfies Dictionary;

export default projectsContent; 